name: Build EXE with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller ivr_status.py ^
            --onefile ^
            --noconsole ^
            --icon note.ico ^
            --add-data "light.qss;." ^
            --add-data "setting.svg;." ^
            --hidden-import pandas ^
            --hidden-import numpy ^
            --hidden-import openpyxl ^
            --additional-hooks-dir=. ^
            --clean ^
            --noconfirm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-Windows
          path: dist/*.exe
